### PR TITLE
Refactor: Replace release script with GitHub Actions workflow

### PR DESCRIPTION
**Pull request by kjohnson**
## Description

This PR replaces the `release.sh` bash script with a GitHub Actions workflow, see `.github/workflows/release.yml`.

The new release workflow is a fork of the one that I use for GiveWP - and have been using for some time. It leverages GitHub secrets to store the SVN secret keys and runs on GitHub servers. New releases are managed through GitHub's native release feature.

See [Using secrets in GitHub Actions](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions).

Secrets to add:
- [ ] `SVN_USERNAME`
- [ ] `SVN_PASSWORD`
- [ ] `GITHUB_TOKEN` (for uploading the release assets)

### CODE REVIEW

**Comment by binarykitchen** [comment]
Nice, thank you. A couple of questions before I merge:

1. Shouldn't this PR also remove what's obsolete, e.g. `release.sh` and `sync-wp.sh` in the `env/dev` folder?
2. PHP v7.4 was picked but latest WordPress runs on v8. May I ask why you picked an older version?
3. Same goes for the old NodeJS version 12 which isn't LTS nor maintained anymore.
4. How's the release script being triggered? Shouldn't we add some npm command to trigger it?

Regarding secrets, the SVN secrets have been added and I've enabled Github actions which should automatically provide a GITHUB_TOKEN, right?

**Comment by kjohnson** [comment]
> Shouldn't this PR also remove what's obsolete, e.g. release.sh and sync-wp.sh in the env/dev folder?

If those scripts are now obsolete, then they can be deleted. I just didn't want to make that assumption.

> PHP v7.4 was picked but latest WordPress runs on v8. May I ask why you picked an older version?

WordPress.org still lists PHP 7.4 as the "recommended" version on the [download page](https://wordpress.org/download/).
While the community is making progress in updating PHP versions there is still a significant usage of PHP 7.4. For compatibility reasons I usually build on PHP 7.4, for now.

> Same goes for the old NodeJS version 12 which isn't LTS nor maintained anymore.

Good point - I see that you have NodeJS v18 configured in `package.json` - I've updated it here.

> How's the release script being triggered? Shouldn't we add some npm command to trigger it?

This script will be automatically triggered when a "release" is created via the GitHub UI. So you prepare changes on your main branch and then "tag" a new release, setting a version number and a changelog. Once the new release is tagged, this script will run.

**Comment by binarykitchen** [comment]
@kjohnson Perfect, all clear. Going to merge that. Thank you so much.

If you want me to pay you a little koha or coffee for your work, please let me know. Making a little income with videomail now :)

**Comment by binarykitchen** [comment]
@kjohnson FYI deployment is broken, some issues around composer, see
https://github.com/binarykitchen/videomail-for-ninja-forms/actions/runs/6918055085/job/18819903885#step:19:164

May I ask why  you have added PHP composer in here? I don't think we need it?

**Comment by kjohnson** [comment]
Weird. I can't remember the last time that I worked on a PHP project without Composer - I guess the last time was when we built this add-on for Ninja Forms 😅  I'll open a new PR for a fix.

**Comment by kjohnson** [comment]
On that note, we probably don't even need to setup PHP for the build either. Without Composer, everything is NPM and Shell.

**Pull request merged**
